/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ibjm.sistemaestoque.view;

import javax.swing.JFrame;

/**
 *
 * @author alcan
 */
public class FrameConfirmar extends javax.swing.JDialog {

	private boolean confirmar;
	
	/**
	 * Creates new form FrameConfirmar2
	 * @param frame
	 */
	public FrameConfirmar(JFrame frame) {
		super(frame, true);
		initComponents();
		setLocationRelativeTo(frame);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInfo = new javax.swing.JLabel();
        lbNao = new javax.swing.JButton();
        lbSim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmação");

        lbInfo.setText("Tem certeza que deseja excluir esse item?");

        lbNao.setText("Não");
        lbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNaoActionPerformed(evt);
            }
        });

        lbSim.setText("Sim");
        lbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInfo)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNao)
                    .addComponent(lbSim))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSimActionPerformed
        confirmar = true;
		dispose();
    }//GEN-LAST:event_lbSimActionPerformed

    private void lbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNaoActionPerformed
        confirmar = false;
		dispose();
    }//GEN-LAST:event_lbNaoActionPerformed

	// Método estático para exibir o frame e retornar a resposta
    public static boolean confirmar(JFrame frame) {
        FrameConfirmar dialog = new FrameConfirmar(frame);
        dialog.setVisible(true);
        return dialog.confirmar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbInfo;
    private javax.swing.JButton lbNao;
    private javax.swing.JButton lbSim;
    // End of variables declaration//GEN-END:variables
}
