/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ibjm.sistemaestoque.view;

import com.ibjm.sistemaestoque.controller.ClienteController;
import com.ibjm.sistemaestoque.controller.FornecedorController;
import com.ibjm.sistemaestoque.controller.NotaFiscalController;
import com.ibjm.sistemaestoque.controller.ProdutoController;
import com.ibjm.sistemaestoque.model.dao.ClienteDAO;
import com.ibjm.sistemaestoque.model.dao.FornecedorDAO;
import com.ibjm.sistemaestoque.model.dao.NotaFiscalDAO;
import com.ibjm.sistemaestoque.model.dao.ProdutoDAO;
import com.ibjm.sistemaestoque.model.vo.Cliente;
import com.ibjm.sistemaestoque.model.vo.Fornecedor;
import com.ibjm.sistemaestoque.model.vo.NotaFiscal;
import com.ibjm.sistemaestoque.model.vo.Produto;
import java.awt.Font;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alcan
 */
public class FramePrincipal extends javax.swing.JFrame {

	String ambiente = "";
	
	/**
	 * Creates new form FramePrincipal
	 */
	public FramePrincipal() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
			JOptionPane.showMessageDialog(this, "Problema ao carregar tema do sistema: " + e);
		}
		initComponents();
		setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
		update();
                
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProdutos = new javax.swing.JToggleButton();
        btnClientes = new javax.swing.JToggleButton();
        btnFornecedores = new javax.swing.JToggleButton();
        btnNotasFiscais = new javax.swing.JToggleButton();
        texFornecedores = new javax.swing.JLabel();
        texNotaFiscal = new javax.swing.JLabel();
        texProdutos = new javax.swing.JLabel();
        texCliente = new javax.swing.JLabel();
        panelOperacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        brnRR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IBJM");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-produto.png"))); // NOI18N
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-cliente.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-fornecedor.png"))); // NOI18N
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        btnNotasFiscais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-fiscal.png"))); // NOI18N
        btnNotasFiscais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasFiscaisActionPerformed(evt);
            }
        });

        texFornecedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texFornecedores.setText("Fornecedores");

        texNotaFiscal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texNotaFiscal.setText("Notas Fiscais");

        texProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texProdutos.setText("Estoque");

        texCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texCliente.setText("Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texProdutos))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texCliente))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texFornecedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotasFiscais, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texNotaFiscal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotasFiscais, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(texNotaFiscal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texProdutos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texFornecedores)
                            .addComponent(texCliente)))
                    .addComponent(btnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelOperacoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setVisible(false);

        jLabel1.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nome", "Inativos" }));
        comboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFiltroActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEditarActionPerformed("Adicionar");
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEditarActionPerformed("Editar");
            }
        });

        brnRR.setText("Remover");
        brnRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRRActionPerformed(evt);
            }
        });

        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout panelOperacoesLayout = new javax.swing.GroupLayout(panelOperacoes);
        panelOperacoes.setLayout(panelOperacoesLayout);
        panelOperacoesLayout.setHorizontalGroup(
            panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacoesLayout.createSequentialGroup()
                        .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacoesLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addGap(516, 516, 516))
                            .addComponent(txtBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(panelOperacoesLayout.createSequentialGroup()
                        .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacoesLayout.createSequentialGroup()
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnRR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(6, 6, 6))))
        );
        panelOperacoesLayout.setVerticalGroup(
            panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOperacoesLayout.createSequentialGroup()
                        .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnAdicionar)
                    .addComponent(brnRR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(panelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
		selecionar("Produtos");
                btnProdutos.setEnabled(false);
                btnClientes.setEnabled(true);
                btnNotasFiscais.setEnabled(true);
                btnFornecedores.setEnabled(true);
                texProdutos.setFont(new Font("Arial", Font.BOLD, 14));
                texCliente.setFont(new Font("Arial", Font.PLAIN, 14));
                texFornecedores.setFont(new Font("Arial", Font.PLAIN, 14));
                texNotaFiscal.setFont(new Font("Arial", Font.PLAIN, 14));
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
		selecionar("Clientes");
                btnProdutos.setEnabled(true);
                btnClientes.setEnabled(false);
                btnNotasFiscais.setEnabled(true);
                btnFornecedores.setEnabled(true);
                texProdutos.setFont(new Font("Arial", Font.PLAIN, 14));
                texCliente.setFont(new Font("Arial", Font.BOLD, 14));
                texFornecedores.setFont(new Font("Arial", Font.PLAIN, 14));
                texNotaFiscal.setFont(new Font("Arial", Font.PLAIN, 14));
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
		selecionar("Fornecedores");
                btnProdutos.setEnabled(true);
                btnClientes.setEnabled(true);
                btnNotasFiscais.setEnabled(true);
                btnFornecedores.setEnabled(false);
                texProdutos.setFont(new Font("Arial", Font.PLAIN, 14));
                texCliente.setFont(new Font("Arial", Font.PLAIN, 14));
                texFornecedores.setFont(new Font("Arial", Font.BOLD, 14));
                texNotaFiscal.setFont(new Font("Arial", Font.PLAIN, 14));
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnNotasFiscaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasFiscaisActionPerformed
		selecionar("NotasFiscais");
                btnProdutos.setEnabled(true);
                btnClientes.setEnabled(true);
                btnNotasFiscais.setEnabled(false);
                btnFornecedores.setEnabled(true);
                texProdutos.setFont(new Font("Arial", Font.PLAIN, 14));
                texCliente.setFont(new Font("Arial", Font.PLAIN, 14));
                texFornecedores.setFont(new Font("Arial", Font.PLAIN, 14));
                texNotaFiscal.setFont(new Font("Arial", Font.BOLD, 14));
    }//GEN-LAST:event_btnNotasFiscaisActionPerformed

	/*
		Clique na janela(ao todo).
	*/
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
		table.setFocusable(false);
		table.setSelectionMode(HIDE_ON_CLOSE);
		update();
    }//GEN-LAST:event_formMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        update();
    }//GEN-LAST:event_tableMouseClicked

    private void brnRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRRActionPerformed
        String msg;
        boolean status = comboBoxFiltro.getSelectedItem().toString().equals("Inativos");
        if (status) {
            msg = "restaurar";
        } else {
            msg = "remover";
        }
        try {
            if (DialogConfirmar.confirmar(this, "Tem certeza que deseja " + msg + " esse item?")) {
                switch (ambiente) {
                    case "Produtos" -> {
                        ProdutoController.setStatusProduto(ProdutoDAO.encontrarProduto(Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString())), status);
                    }
                    case "Clientes" -> {
                        ClienteController.setStatusCliente(ClienteDAO.encontrarCliente(Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString())), status);
                    }
                    case "Fornecedores" -> {
                        FornecedorController.setStatusFornecedor(FornecedorDAO.encontrarFornecedor(Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString())), status);
                    }
                    case "NotasFiscais" -> {
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        selecionar(ambiente);
    }//GEN-LAST:event_brnRRActionPerformed

    private void comboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFiltroActionPerformed
        selecionar(ambiente);
    }//GEN-LAST:event_comboBoxFiltroActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        selecionar(ambiente);
    }//GEN-LAST:event_txtBuscarKeyReleased

	private void btnAdicionarEditarActionPerformed(String ambienteBtn) {
		String acao = "";
		int codSelecionado = 0;
		if (ambienteBtn.equals("Adicionar")) {
			acao = "Adicionar";
			codSelecionado = -1;
		} else if (ambienteBtn.equals("Editar")) {
			acao = "Editar";
			codSelecionado = Integer.parseInt(table.getValueAt(table.getSelectedRow(), 0).toString());
		}
		
		switch (ambiente) {
		case "Produtos" -> {
			// Frame Produto
			FrameProduto fpdt = new FrameProduto(this, acao, codSelecionado);
			fpdt.setVisible(true);
			}
		case "Clientes" -> {
			// Frame Cliente
			FrameCliente fc = new FrameCliente(this, acao, codSelecionado);
			fc.setVisible(true);
			}
		case "Fornecedores" -> {
			// Frame Fornecedor
			FrameFornecedor ff = new FrameFornecedor(this, acao, codSelecionado);
			ff.setVisible(true);
			}
		case "NotasFiscais" -> {
			// Frame NotaFiscal
			FrameNotaFiscal fnf = new FrameNotaFiscal(this);
			fnf.setVisible(true);
			}
		}
	}
	
	/*
		De acordo com o que o usuário selecionar, deixa o botão de tabela ativo ou não.
	*/
	public void selecionar(String ambienteSelecionado) {
		try {

			String[] cabecalho = null;
			Object[][] arrayDados = null;

			// Deixa o selecionado ativo
			switch (ambienteSelecionado) {
			case "Produtos" -> {
				cabecalho = new String[] {"Codigo", "Status", "Marca", "Descrição", "Valor Compra", "Valor Venda", "Quantidade", "Data Cadastro"};
				ArrayList<Produto> arrayProdutos = ProdutoDAO.listarProdutos(comboBoxFiltro.getSelectedItem().toString(), txtBuscar.getText());
				arrayDados = ProdutoController.obterDados(arrayProdutos);
				}
			case "Clientes" -> {
				cabecalho = new String[] {"Codigo", "Status", "Nome", "CPF", "RG", "Endereço", "Telefone", "Email", "Data Cadastro"};
				ArrayList<Cliente> arrayClientes = ClienteDAO.listarClientes(comboBoxFiltro.getSelectedItem().toString(), txtBuscar.getText());
				arrayDados = ClienteController.obterDados(arrayClientes);
				}
			case "Fornecedores" -> {
				cabecalho = new String[] {"Codigo", "Status", "Nome", "CNPJ", "Inscrição Estadual", "CNAE", "Endereço", "Telefone", "Email", "Data Cadastro"};
				ArrayList<Fornecedor> arrayFornecedores = FornecedorDAO.listarFornecedores(comboBoxFiltro.getSelectedItem().toString(), txtBuscar.getText());
				arrayDados = FornecedorController.obterDados(arrayFornecedores);
				}
			case "NotasFiscais" -> {
	//			cabecalho = new String[] {"Codigo", "Status", "Nome", "CNPJ", "Endereço", "Email", "Telefone", "Data Cadastro"};
	//			ArrayList<NotaFiscal> arrayNotasFiscais = NotaFiscalDAO.listarFornecedores();
	//			arrayDados = NotaFiscalController.obterDados(arrayNotasFiscais);
				}
			}

			// Altera a tabela
			table.setModel(new DefaultTableModel(arrayDados, cabecalho) {
				@Override
				public boolean isCellEditable(int row, int col) {
					return false;
				}
			});
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, e);
		}
		
		ambiente = ambienteSelecionado;
		update();
	}
	
	/*
		Atualiza os componentes do frame.
	*/
	private void update() {
		// Verifica a ação do botão excluir
		if (comboBoxFiltro.getSelectedItem().toString().equals("Inativos")) {
			brnRR.setText("Restaurar");
		} else {
			brnRR.setText("Remover");
		}
		
		// Deixa ativado ou não as operações
		if (ambiente.equals("")) {
			txtBuscar.setEnabled(false);
			comboBoxFiltro.setEnabled(false);
			btnAdicionar.setEnabled(false);
		} else {
			txtBuscar.setEnabled(true);
			comboBoxFiltro.setEnabled(true);
			btnAdicionar.setEnabled(true);
		}
		
		// Mostra ou não as opções de editar ou remover se a tabela estiver selecionada
		if (table.getSelectedRow() != -1) {
			btnEditar.setVisible(true);
			brnRR.setVisible(true);
		} else { 
			btnEditar.setVisible(false);
			brnRR.setVisible(false);
		}
		
		revalidate();
		repaint();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRR;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JToggleButton btnClientes;
    private javax.swing.JButton btnEditar;
    private javax.swing.JToggleButton btnFornecedores;
    private javax.swing.JToggleButton btnNotasFiscais;
    private javax.swing.JToggleButton btnProdutos;
    private javax.swing.JComboBox<String> comboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelOperacoes;
    private javax.swing.JTable table;
    private javax.swing.JLabel texCliente;
    private javax.swing.JLabel texFornecedores;
    private javax.swing.JLabel texNotaFiscal;
    private javax.swing.JLabel texProdutos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
